name: Sample Test Run with vscode

# Token gets reset
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      

    - name: kubectl
      run: |
        echo 'alias k=kubectl' >>/home/runner/.bashrc
        echo 'complete -F __start_kubectl k' >>/home/runner/.bashrc
        echo 'PATH="${PATH}:${HOME}/.krew/bin"'>>/home/runner/.bashrc
        sudo -i -u runner ./install_krew.sh 
        git clone https://github.com/TacoMonk/dotfiles.git
        cd dotfiles/
        make kind 
        
    
    - uses: mchirico/vscode-action@v1
      with:
        ngrok_token: ${{ secrets.NGROK_TOKEN }}
        vscode_port: 8779
        wait_duration: 17hr
